#!/usr/bin/env node
/**
 * Test-spec generator: scaffolds a run-tests.js JSON spec for a transform
 * function, given the function name, input type, and output type.
 *
 * Sample input values are generated from the input type's definition (nested objects
 * and lists included). Expected values are derived by name-matching properties
 * (the standard transform convention) — review and adjust for any custom logic.
 *
 * Usage: node generate-test.js <functionName> <InputType> <OutputType> [typesDir] [-o out.json]
 * Defaults: typesDir = ./types (if present), output = ./test/<functionName>.test.json
 */
const fs = require('fs');
const path = require('path');
const { loadTypes } = require('./lib/types');

const localName = (t) => t.replace(/^\w+:/, '');
const isPrim = (t) => t.startsWith('xs:');

const SAMPLES = {
  'xs:string': (p) => `${p}_value`,
  'xs:boolean': () => true,
  'xs:integer': () => 42, 'xs:int': () => 42, 'xs:long': () => 42, 'xs:short': () => 7,
  'xs:decimal': () => 9.99, 'xs:double': () => 9.99, 'xs:float': () => 1.5,
  'xs:date': () => '2026-01-15', 'xs:dateTime': () => '2026-01-15T10:00:00', 'xs:time': () => '10:00:00',
};

/** Generate a full sample value for a type from its definition. */
function buildSample(typeName, types, depth) {
  if (depth > 5) return null; // guard against recursive types
  const def = types[typeName];
  if (!def) throw new Error(`Type "${typeName}" not found in the type definitions`);
  const obj = {};
  for (const [prop, d] of Object.entries(def.properties)) {
    const one = isPrim(d.xsType)
      ? (SAMPLES[d.xsType] || SAMPLES['xs:string'])(prop)
      : buildSample(localName(d.xsType), types, depth + 1);
    obj[prop] = d.isList ? [one, one] : one;
  }
  return obj;
}

/** Derive expected output by name-matching source value onto the target type. */
function mapExpected(srcVal, S, T, types, depth) {
  if (srcVal == null || depth > 5) return null;
  const src = types[S], tgt = types[T];
  const out = {};
  for (const [prop, tDef] of Object.entries(tgt.properties)) {
    const sDef = src.properties[prop];
    if (!sDef || sDef.isList !== tDef.isList) { out[prop] = tDef.isList ? [] : null; continue; }
    const sPrim = isPrim(sDef.xsType), tPrim = isPrim(tDef.xsType);
    const v = srcVal[prop];
    if (tDef.isList) {
      out[prop] = (v || []).map(item =>
        sPrim && tPrim ? item :
        !sPrim && !tPrim ? mapExpected(item, localName(sDef.xsType), localName(tDef.xsType), types, depth + 1) : null);
    } else if (sPrim && tPrim) {
      out[prop] = v !== undefined ? v : null;
    } else if (!sPrim && !tPrim) {
      out[prop] = mapExpected(v, localName(sDef.xsType), localName(tDef.xsType), types, depth + 1);
    } else {
      out[prop] = null;
    }
  }
  return out;
}

function generateSpec(fnName, inputType, outputType, types) {
  const fullInput = buildSample(inputType, types, 0);
  const emptyExpected = {};
  for (const [prop, d] of Object.entries(types[outputType].properties))
    emptyExpected[prop] = d.isList ? [] : null;
  return {
    _note: 'Generated by generate-test.js — expected values assume name-matched mapping; review for custom logic.',
    function: fnName,
    cases: [
      {
        name: `full ${inputType} maps to ${outputType}`,
        input: { type: inputType, value: fullInput },
        expect: { type: outputType, value: mapExpected(fullInput, inputType, outputType, types, 0) },
      },
      {
        name: `empty ${inputType} yields null/empty properties`,
        input: { type: inputType, value: {} },
        expect: { type: outputType, value: emptyExpected },
      },
    ],
  };
}

// ---- CLI ----
if (require.main === module) {
  const args = process.argv.slice(2);
  const oIdx = args.indexOf('-o');
  const outFile = oIdx !== -1 ? args.splice(oIdx, 2)[1] : null;
  const [fnName, inputType, outputType, typesDirArg] = args;
  if (!fnName || !inputType || !outputType) {
    console.error('Usage: node generate-test.js <functionName> <InputType> <OutputType> [typesDir] [-o out.json]');
    process.exit(2);
  }
  const typesDir = typesDirArg || (fs.existsSync('types') ? 'types' : '.');
  try {
    const types = loadTypes(typesDir);
    const spec = generateSpec(fnName, inputType, outputType, types);
    const out = outFile || path.join(fs.existsSync('test') ? 'test' : '.', `${fnName}.test.json`);
    fs.writeFileSync(out, JSON.stringify(spec, null, 2) + '\n');
    console.log(`Wrote ${out} (${spec.cases.length} cases, types from ${typesDir}/)`);
    console.log(`Run: node run-tests.js <script.js> ${out} ${typesDir}`);
  } catch (e) {
    console.error(`ERROR: ${e.message}`);
    process.exit(1);
  }
}

module.exports = { generateSpec, buildSample, mapExpected };
