/* Generated by generate.js on 2026-07-06 — CustomerWS -> Customer (Rhino/ES5, IBM BAW) */

/**
 * Converts a AddressWS object to a Address object.
 * @param {AddressWS} addressWS - The AddressWS object to be converted.
 * @returns {Address} - The converted Address object.
 */
function convertAddressWSToAddress(addressWS) {
    if (addressWS == null) {
        return null;
    }
    var result = new tw.object.Address();
    result.line1 = addressWS.line1;
    result.line2 = addressWS.line2;
    result.postcode = addressWS.postcode;
    result.type = addressWS.type;
    // NOTE: source properties not mapped (no counterpart on Address): line3
    return result;
}

/**
 * Converts a CustomerWS object to a Customer object.
 * @param {CustomerWS} customerWS - The CustomerWS object to be converted.
 * @returns {Customer} - The converted Customer object.
 */
function convertCustomerWSToCustomer(customerWS) {
    if (customerWS == null) {
        return null;
    }
    var result = new tw.object.Customer();
    result.name = customerWS.name;
    result.age = customerWS.age;
    result.homeAddress = convertAddressWSToAddress(customerWS.homeAddress);
    result.otherAddresses = new tw.object.listOf.Address();
    if (customerWS.otherAddresses != null) {
        for (var i = 0; i < customerWS.otherAddresses.listLength; i++) {
            result.otherAddresses.insertIntoList(result.otherAddresses.listLength, convertAddressWSToAddress(customerWS.otherAddresses[i]));
        }
    }
    // TODO: "Customer.customerId" has no matching property on "CustomerWS" — map manually if needed
    // NOTE: source properties not mapped (no counterpart on Customer): internalRef
    return result;
}
